#!/bin/bash
srcHash=0
inpHash=0
tempInp=1
tempSrc=1

while [ -n "$1" ]
do
	tempSrc=`shasum $1`
	if [ -n "$2" ]
	then
		tempInp=`shasum $2`
	fi
	if [ "$srcHash" != "$tempSrc" ] || [ "$inpHash" != "$tempInp" ]  
	then
		g++ $1
		echo "Compiled"
		if [ -n "$2" ]
		then
			inpHash="$tempInp"
			./a.out < $2
		else
			./a.out
		fi
		srcHash="$tempSrc"
		echo 
	fi
	sleep 2
done
if [ -z "$1" ]
then
	echo "Please specify source file.Error Exiting..."
fi
