#!/bin/bash
srcHash=0
inpHash=1

tempInpHash=1
tempSrcHash=1

#handling fileExtension for c and c++ compiling
fileExtension=`echo $1 | cut -d "." -f 2`
if [ "$fileExtension" = "cpp" ]
then
	compiler="g++"
else
	compiler="gcc"
fi

#runs forever unless source isn't mentioned
while [ -n "$1" ]
do
	#tempSrcHash and temoInpHash to hold the intermediate hash to compare with previous hash of the file to detect change in src and input
	tempSrcHash=`shasum $1`
	if [ -n "$2" ]
	then
		tempInpHash=`shasum $2`
	fi

	#checks for change either in source or input files
	if [ "$srcHash" != "$tempSrcHash" ] || [ "$inpHash" != "$tempInpHash" ]
	then
		#clears screen for output
		reset

		#compiles according to fileExtension
		`$compiler $1`
		echo "Compiled at `date`"
	
		#if input file is present , feed it to a.out or else...
		if [ -n "$2" ]
		then
			#if no input file is given , inpHash == tempInpHash == 1 holds forever	
			inpHash="$tempInpHash"
			inputFile="$2"
		else
			inputFile=""
		fi
	
		#if a.out file exists...	
		if [ -e "a.out" ]
		then
			cat $2 | ./a.out
		fi

		srcHash="$tempSrcHash"
		echo 
	fi
	sleep 2
done
if [ -z "$1" ]
then
	echo "Please specify source file.Error Exiting..."
fi
